TestLive1/TestLive/urls.py
from django.conf.urls import url
from . import views

app_name = 'TestLive'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^TestLive/login/$', views.login, name = 'login'),
    url(r'^TestLive/blogs/$', views.blogs, name='blogs'),
    url(r'^TestLive/discussion/$', views.discussions, name = 'discussion'),
    url(r'^TestLive/promo/$', views.promo, name='promo'),
    url(r'^TestLive/refer/$', views.refer, name = 'refer'),
    url(r'^TestLive/courses/$', views.courses, name = 'course'),
    url(r'^TestLive/exams/$', views.exams, name='exam'),
    url(r'^TestLive/home/$', views.home, name = 'home'),
    url(r'^TestLive/pass/$', views.passes, name='passes'),
    url(r'^TestLive/sign_up/$', views.sign_up, name = 'sign_up'),
    url(r'^TestLive/gk_CA/$', views.gk_CA, name='gk_CA'),
    url(r'^TestLive/practise/$', views.practise, name = 'practise'),
    url(r'^TestLive/upload/$', views.upload, name='upload'),

]

TestLive1/TestLive1/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django import views
from django.contrib.auth import views as auth_view
from TestLive import views as TestLive_view
from TestLive.syndicate import LatestEntries
from blogs import views as blog_view,urls as blog_url
from payment import views as payment_view
from exam_papers import views as examPaper_view
from emails import views as email_view



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('login/',auth_view.LoginView.as_view(template_name='TestLive/login.html'),name='login'),
    url('logout/',auth_view.LogoutView.as_view(template_name='TestLive/logout.html'),name='logout'),
    url('feeds/',LatestEntries(),name='feeds'),
    url('',include(blog_url),name='blog'),
]



urlpatterns+=[
   url('register/',TestLive_view.register,name='register'),
   url('profile/',TestLive_view.profile,name='profile'),
   url('csv_view/',TestLive_view.csv_view,name='csv_view'),
]



urlpatterns+=[
   url('exam_paper/',examPaper_view.paper,name='paper'),
   url('email/',email_view.send_email,name='emails'),
   url('payment/',payment_view.payment,name='payment'),
]



urlpatterns+=[
   url('',blog_view.update_blog,name='blog'),
]



if settings.DEBUG:
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

TestLive1/blogs/urls.py
from django.conf.urls import url
from .views import blogList
from . import views


urlpatterns=[
   #url('',blogList.as_view(template_name='blogs/blogList.html'),name='blogList'),
   url('',views.list_blog,name='list_blog'),
]

TestLive1/exam/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
   url('exam/',views.paper_view,name='paper_view'),
]

TestLive1/TestLive/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.db import models

from django.contrib.auth.models import User


class EmailModel(models.Model):
      subject=models.CharField(max_length=100)
      message=models.CharField(max_length=10000)
      from_email=models.OneToOneField(User,on_delete=models.CASCADE)
      to_email=models.EmailField()

      def __str__(self):
          return self.from_email.username     


class Profile(models.Model):
      user=models.OneToOneField(User,on_delete=models.CASCADE)
      image=models.ImageField(default='default.jpg',upload_to='profile_pics')

      def __str__(self):
          return self.user.username

TestLive1/blogs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class blogModel(models.Model):
      user=models.TextField(max_length=150)
      date=models.DateTimeField()
      title=models.CharField(max_length=150)
      blog=models.CharField(max_length=1000)
      
      class Meta:
          ordering=["user"]

      def __str__(self):
          return self.title


"""
@receiver(post_save,sender=User)
def create_user_blog(sender,instance,created,**kwargs):
    if created:
       blogModel.objects.create(title=instance)


@receiver(post_save,sender=User)
def save_user_blog(sender,instance,**kwargs):
    instance.blogmodel.save()

"""

TestLive1/exam/models.py
from django.db import models

class paper(models.Model):
      type=models.CharField(max_length=20)
      time=models.DateTimeField()
      duration=models.DecimalField(max_digits=3,decimal_places=2)
      file=models.FileField()

      def __str__(self):
          return self.type

TestLive1/TestLive/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import EmailModel,Profile


class UserRegistrationForm(UserCreationForm):
      email=forms.EmailField()
      
      class Meta:
            model=User
            fields=['username','email','password1','password2']


class EmailForm(ModelForm):
      to_email=forms.EmailField()      
      class Meta:
            model=EmailModel
            fields=['subject','message','from_email','to_email']      


class UserUpdateForm(ModelForm):
      email=forms.EmailField()

      class Meta:
            model=User
            fields=['username','email']


class ProfileUpdateForm(ModelForm):
      class Meta:
            model=Profile
            fields=['image']

TestLive1/blogs/forms.py
from django.forms import ModelForm
from .models import blogModel
from django import forms


class blogForm(ModelForm):
    email=forms.EmailField()
    class Meta:
        model=blogModel
        fields=['email','title','blog']

TestLive1/TestLive/views.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,StreamingHttpResponse
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm,EmailForm,ProfileUpdateForm,UserUpdateForm
from .models import Profile
from django.core.mail import BadHeaderError,send_mail
import csv
from django.template import Context,loader
from .models import Exam, Login, Set, Analytic, User, Registration, Plan, E_Commerce, Payment, Choose_Plan, Query, Contact_Us, Upload_Form 
from .forms import fileUpload, NameForm


def register(request):
    if request.method=='POST':
       form=UserRegistrationForm(request.POST)
       if form.is_valid():
          form.save()
          username=form.cleaned_data.get("username")
          return HttpResponseRedirect('')
    else:
        form=UserRegistrationForm()
    return render(request,'TestLive/register.html',{'form':form})



@login_required
def profile(request):
    try:
        profile=request.user.profile
    except Profile.DoesNotExist:
        profile=Profile(user=request.user)
    if request.method=='POST':
       u_form=UserUpdateForm(request.POST,instance=request.user)
       p_form=ProfileUpdateForm(request.POST or None,request.FILES,instance=profile)
       if u_form.is_valid() and p_form.is_valid():
          p_form.save()
          u_form.save()
          return HttpResponseRedirect('')
    else:
        u_form=UserUpdateForm(instance=request.user)
        p_form=ProfileUpdateForm(instance=request.user.profile)

    context={
             'u_form':u_form,
             'p_form':p_form
            }
    return render(request,'TestLive/profile.html',context) 


def feeds(request):
    return render(request,'TestLive/feeds.html')

"""
def send_email(request):
    if request.method=='POST':
       email_form=EmailForm(request.POST)
       if email_form.is_valid():
          email_form.save()
          send_mail('subject','message','email_form.from_email',['to_email@gmail.com'],fail_silently=False)
          return HttpResponse('Hello')  
    else:
        #email_form=EmailForm()
        return HttpResponse("Enter Valid Form")
    return redirect(request,'TestLive/email.html',{'email':email_form})
"""    



def send_email(request):
    if request.method=='POST':
       subject = request.POST.get(request.POST,'subject', '')
       message = request.POST.get('message', '')
       from_email = 'TestLive@ac.in'
       if subject and message and from_email:
          try:
              send_mail(subject, message, from_email, ['admin@example.com'])
          except BadHeaderError:
              return HttpResponse('Invalid header found.')
          return HttpResponseRedirect('')
    else:
        return HttpResponse('Make sure all fields are entered and valid.')
    return redirect(request,'TestLive/email.html')



class Echo():
      def write(self,value):
          return value


def csv_view(request):
    """
    response=HttpResponse(content_type='text/csv')
    response['Content-Disposition']='attachment;filename="Charan_PG.xlsx"'
    csv_data=(
        ('First row','Foo','Bar','Baz'),
        ('Second row','A','B','Testing'),
    )
    
    t=loader.get_template('csv_to_txt.txt')
    c=Context({
      'data':csv_data,
    })
    response.write(t.render(c))
    return response

    """
    rows=(["Row {}".format(idx),str(idx)] for idx in range(65536))
    pseudo_buffer=Echo()
    writer=csv.writer(pseudo_buffer)
    response=StreamingHttpResponse((writer.writerow(row) for row in rows),content_type="text/csv")
    response['Content-Disposition']='attachment;filename="Charan_PG.xlsx"'
    return response


def sign_up(request):
    if request.method == "POST":
        form=NameForm(request.POST)
        if form.is_valid:
            return HttpResponseRedirect("/detail/")
    else
       form=NameForm()
    return render(request,"sign_up.html",{'form':form})

def contact_form(request):
       subject=request.POST.get('subject', '')
       message=request.POST.get('message', '')
       sender=request.POST.get('sender', '')
       cc_myself=request.POST.get('cc_myself', '')
       bcc=request.POST.get('bcc','')
       reciepents=['TestLive@edu.in']
       if cc_myself:
          reciepents.append(sender)
       if bcc:
          reciepents.append(bcc)
       if subject and message and sender and reciepents:
          try:
              send_email(subject,message,sender,receipents)
              return HttpResponseRedirect("/home/contactform")
          except BadHeaderError:
            return HttpResponse("failed")
       else:
          return HttpResponse("Enter each option again.")
       
def home(request):
    home = Plan.objects.all()
    return render(request, 'home.html', {'Name': home})

def login(request):
    login = Login.objects.all()
    return render(request, 'login.html', {'latest_upload':login})

def blogs(request):
    blog = Query.objects.all()
    return render(request, 'blogs.html', {'Name': blog})

def discussions(request):
    discussion = Contact_Us.objects.all()
    return render(request, 'discussion.html', {'Name': discussion})

def promo(request):
    promo = Analytics.objects.all()
    return render(request, 'promo.html', {'Name': promo})

def refer(request):
    refer = Set.objects.all()
    return render(request, 'refer.html', {'Name': refer})

def courses(request):
    course = Exam.objects.all()
    return render(request, 'courses.html', {'Name': course})

def exams(request):
    exam = Exam.objects.all()
    return render(request, 'exams.html', {'Name': exam})

def passes(request):
    passes = Plan.objects.all()
    return render(request, 'pass.html', {'Name': passes})

def gk_CA(request):
    Gk_CA = Exam.objects.all()
    return render(request, 'gk_CA.html', {'Name': Gk_CA})

def practise(request):
    practise = Set.objects.all()
    return render(request, 'practise.html', {'Name': practise})

def upload(request):
    upload = Upload_Form.objects.all()
    return render(request, 'upload.html', {'Name': upload})

"""
def file_upload(request):
  if request.method == 'POST': 
     form = fileUpload(request.POST, request.FILES)
     if form.is_valid():
        handle_fileUpload(request.FILES['file'])
        return HttpResponseRedirect('/success/url/')
  else:
      form = fileUpload()
  return render(request, 'detail.html', {'form' : form})
"""

def index(request):
    Name = Registration.objects.all()
    return render(request, 'home.html', {'Name': Name})

TestLive1/blogs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.core.paginator import Paginator
from .forms import blogForm
from .models import blogModel



class blogList(ListView):
    model=blogModel



@login_required
def update_blog(request):
    if request.method=='POST':
       blog=blogForm(request.POST,instance=request.user)       
       if blog.is_valid():
          blog.save()
          #user=form.cleaned_data.get('username')
          return HttpResponseRedirect('/blogs/')
    else:
       blog=blogForm(instance=request.user)
    return render(request,'blogs/blogs.html',{'blog':blog})



def list_blog(request):
    blog=blogModel.objects.all()
    p=Paginator(blog,1)
    page=request.GET.get('page',1)
    p1=p.page(page)
    return render(request,'blogs/blogList.html',{'page':p1})    
    

TestLive1/exam/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.core.paginator import Paginator
from .models import paper


def paper_view(request):
    if paper.type=="IIT_Advance":
       p=paper.objects.get(type="IIT_Advance")
    elif paper.type=="IIT_Mains":
       p=paper.objects.get(type="IIT_Mains")
    elif paper.type=="Gate_Mains":
       p=paper.objects.get(type="IIT_Mains")
    elif paper.type=="Gate_ME":
       p=paper.objects.get(type=="IIT_Mains")
    elif paper.type=="IIT_Mains":
       p=paper.objects.get(type=="IIT_Mains")
    else:
       p=paper.objects.get(type=="IIT_Mains")
    p1=Paginator(p,10)
    page=request.GET.get('page',1)
    p1=p1.page(page)
    return render(request,'exam/exam1.html',{'page':p1})
    
     

TestLive1/TestLive/templates/TestLive/blogs.html
<h1>Blog.</h1>

TestLive1/TestLive/templates/TestLive/contact_list.html
<h1>Contacts</h1>

<ul>
  {% for contact in object_list %}
    <li class="contact">{{ contact }}</li>
  {% endfor %}
</ul>

<a href="{% url "contacts-new" %}">add contact</a>

TestLive1/TestLive/templates/TestLive/courses.html
 <h1>courses.</h1>

TestLive1/TestLive/templates/TestLive/detail.html
<html>
 <head>
  <title>TestLive</title>
 </head>
 <body>
	 <header>
          <h1>
	   <center>
	    <div class='popup' onclick='return popup()'>
             <a href="#">TestLive
	     </a>
	    </div>
	   </center> 
            <div>
             <form action="{% url 'TestLive:index' %}" method="post">
	     {% csrf_token %}
	     {% for Exam in latest_upload %}
	        <input type="radio" name="Exam" id="Exam{{forloop.counter}}" value="{{Exam.id}}"/>
		<label for="{{forloop.counter}}">{{Exam.Exam_Type}}</label><br/>
	     {% endfor %}
	     <input type="submit" value="upload" />
	     </form>
	    </div>
	  </h1>
	  <h4><a class="reference internal" href = "../TestLive">Exams</a></h4>
 {% if latest_upload %}
     <ul>
      {% for Exam in latest_upload %}
         <li>
         <a href = "{% url 'TestLive:index'%}" target = "_blank">{{Exam.Exam_Type}}
           </a>
	     <div>
	         <ul>
		    <li>
		       <a href = "/TestLive/{{Exam.id}}/" target = "_blank">{{Exam.Exam_Type}} Paper</a>
		    </li>
		 </ul>
	     </div>
	 </li>
      {% endfor %}
     </ul>
 {% else %}
     <p>No TestLive.</p>
 {% endif %}
    </div>
  </header>
  <footer>
  </footer>
 </body>
</html>

TestLive1/TestLive/templates/TestLive/discussion.html
<h1>Discussions.</h1>

TestLive1/TestLive/templates/TestLive/exams.html
<h1>Exams</h1>

TestLive1/TestLive/templates/TestLive/gk_CA.html
<h1>GK & CA.</h1>

TestLive1/TestLive/templates/TestLive/login.html
<!DOCTYPE html>
<html>
 <head>
  <title>TestLive | login</title>
  <style type="text/css">
   div{
        display:block;
	margin:0px;
   }

   #wrapper{
        width:1000px;
        height:1500px;  
   }

   #upleft{
        width:60%;
        height:240%;
	background-image:url("/static/images/logo-testlive.png");
        background-size:1800px, 180px;
        background-repeat: no-repeat;   
	float:left;
	padding:20px;
   }

   #upright{
        width:40%;
	height:240%;
	background:rgb(100,68,100);
	float:left;
	font-size:15px;
	margin:0px;
   }

   #below{
       float:left;
       height:0%;
       width:0%;
       background:green;
   }

   #images{
      background-image:url("/static/images/logo-testlive.png");
      background-size: 200%, 140%;
      background-repeat: no-repeat;
   }

   #title{
           padding:0px 20px;
   }
 
   #h{
      margin:0px;
   }
  </style>
 </head>
 <body>
  <div> <!-- id="wrapper" -->
   <div id="upleft">
    <br/><br/><br/>
    <h1 style="color:brown; margin:0px">Test<cite style="color:lightgreen;"><em>Live</em></cite></h1><br/>
    <h1 style="color:brown;">India's Reputed Live Mock Preparation Site</h1>
    <div style="color:black; font-size:30px;">for</div>
    <div style="color:black; font-size:30px; margin:0px">Bank,SSC,RRB,GATE,JEE,UPSC</div>
    <div style="color:black; font-size:30px; margin:0px"> & other exams</div>
    <h1><div style="color:purple;margin:0px">Flexible Test Time Period</div></h1>
    <div style="color:black; font-size:20px; margin:0px">(check description for validity)</div><br/>
    <div style="color:black;font-size:20px;"><i>Based on latest pattern and syllabus of exams</i></div>
    <br/>
    <img src="/static/images/desktop.png" alt="desktop"><div style="color:black; padding:4px">Latest Pattern & Web Interface</div>
    <img src="/static/images/ranking.png" alt='ranking'><div style="color:black; padding:4px">All India Rank Analysis</div>
    <img src="/static/images/pieAnalysis.png" alt='pie-chart'><div style="color:black; padding:4px">Detailed Analysis & Solutions</div>          
    <img src="/static/images/desktopApp.png" alt='desktop-app'><div style="color:black; padding:4px">Available on Desktop & Android App</div>
   </div>

 <!-- RightHandSide. ---------------------------------------------------------------------------------- -->

   <div id="upright">
    <br/><br/><br/>
    <br/>
    <center><img src="/static/images/logo-testlive.png" alt="logo-testlive.png"></center>
      <br/><br/>
      <div style="color:white; font-size:25px;"><center>REGISTER NOW</center></div>
      <div style="color:white; font-size:20px;"><center>SUBSCRIPTIONS AVAILABLE</center>
      <div style="color:white; font-size:20px;"><center>FREE!</center>
     <br/>
     <center>
      <div style="color:white; font-size:15px;">
       <a href="http://www.facebook.com/login" target="_blank">FACEBOOK</a>
       <a href="https://accounts.google.com/ServiceLogin/identifier?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin" target="_blank">GOOGLE+</a>
      </div>   
     </center><br/>
     <div style="color:white; font-size:15px;"><center>OR</center><br/></div>
      <div class='sub-menu'> 
       <br/>
      {% for Name in Registration.Email %}
      <a href="#">{{ Registration.Email}}</a>
      {% endfor %}
      <div style="color:white; font-size:15px;">Name<center><input  alt="name"></input></center></div><br/><br/>
      <div style="color:white; font-size:15px;">Email<center><input type="text" alt="email"></center></input></div><br/><br/>
      <div style="color:white; font-size:15px;">Password<center><input type="password" alt="pwd"></input></center></div><br/><br/>
      <div style="color:white; font-size:15px;">Mobile No.<center><input type="digits" alt="mobile."></input></center></div><br/><br/>
      <div type="form" style="color:white; font-size:18px;"><a href="http://127.0.0.1:8000/admin/TestLive/registration/add/" type="button" target="_blank"><h4><center>REGISTER NOW</center></a></div>
      <div style="color:black; font-size:15px;"><center>Already registered. Please</center>
      <div style="color:purple; font-size:15px;"><a href="http://127.0.0.1:8000/admin/TestLive/login/add/" target="_blank"><center>login</center></a></div>
     </table>
    </div>
   </div>
  </div> 
 </body>
</html>

TestLive1/TestLive/templates/TestLive/pass.html
<h1>Pass.</h1>

TestLive1/TestLive/templates/TestLive/practise.html
<h1>practise</h1>

TestLive1/TestLive/templates/TestLive/promo.html
<h1>Promo.</h1>

TestLive1/TestLive/templates/TestLive/refer.html
<h1>Refer.</h1>

TestLive1/TestLive/templates/TestLive/sign_up.html
<h1>Sign Up</h1>
<form action="/SignUp/" method="post">
 <label for='your_name'>Email</label>
 <input id="your_name" type="text" name="email" value="{{your_name}}">
 <label for id='password'>Password</label>
 <input id="password" type="password" name="password" value="{{password}}">
 <label for id='new_pwd'>Confirm Password</label>
 <input id="new_pwd" type="password" name="confirm password" value="{{new_pwd}}">
 <input type="submit" value="OK">
</form>

TestLive1/TestLive/templates/TestLive/upload.html
<!DOCTYPE html>
<html>
     <head>
          <title>TestLive</title>

     </head>
     <body>
          <header>
		  
          <header>
          <form enctype="multipart/form-data" method="post" action="/foo/">
	  
	  </form>
          <footer>
	  
	  </footer>
     </body>
</html>